---
title: "ex estatapi"
author: "okiyuki99"
date: '`r Sys.Date()`'
output:
  html_document:
    number_sections: true
    toc: true
    toc_float: true
    fig_width: 7
    fig_height: 4.5
    fig_caption: true
    theme: cosmo
    highlight: tango
    code_folding: hide
    code_download: true
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_dir = "../docs/") })
---

# Summary 

* eStat APIを試す
* https://qiita.com/nozma/items/f88f5cc60ab63461deae

# Preparations {.tabset .tabset-fade .tabset-pills}

## libraries

```{r, message=F, warning=F}
options(scipen=10)

library(tidyverse)
library(knitr)
library(httr)

library(kableExtra)
library(listviewer)
```

## Load appId

```{r}
appId <- Sys.getenv("ESTAT_API_APPID")
```

# Step 1 統計表IDを確認する

たまに失敗する

```{r}
res <- httr::GET(
  url = "https://api.e-stat.go.jp/rest/3.0/app/json/getStatsList",
  query = list(
    appId = appId,
    searchWord = "普通貿易統計"
  )
)

res_content <- httr::content(res)
#listviewer::jsonedit(res_content)
```

atidを使って次のstepでデータをダウンロードする

```{r}
df_meta <- data.frame(
  atid = purrr::map_chr(res_content$GET_STATS_LIST$DATALIST_INF$TABLE_INF, "@id"),
  STATISTICS_NAME = purrr::map_chr(res_content$GET_STATS_LIST$DATALIST_INF$TABLE_INF, "STATISTICS_NAME"),
  TITLE = purrr::map_chr(res_content$GET_STATS_LIST$DATALIST_INF$TABLE_INF, "TITLE"),
  SURVEY_DATE = purrr::map_chr(res_content$GET_STATS_LIST$DATALIST_INF$TABLE_INF, "SURVEY_DATE"),
  OPEN_DATE = purrr::map_chr(res_content$GET_STATS_LIST$DATALIST_INF$TABLE_INF, "OPEN_DATE"),
  UPDATED_DATE = purrr::map_chr(res_content$GET_STATS_LIST$DATALIST_INF$TABLE_INF, "UPDATED_DATE"),
  stringsAsFactors = F
)
```

# Step 2  統計データ取得

```{r}
df_meta %>%
  filter(atid %in% c("0003334003")) %>%
  pull(TITLE) 
```

```{r}
posi <- 1
df <- data.frame()
while(TRUE){
  res <- httr::GET(
    # url = "https://api.e-stat.go.jp/rest/3.0/app/json/getStatsData",
    url = "https://api.e-stat.go.jp/rest/3.0/app/getSimpleStatsData",
    query = list(
      appId = appId,
      statsDataId = "0003334003",
      startPosition = (posi - 1) * 100000 + 1,
      limit = 100000 # 10万まで,
    )
  )
  res_content <- httr::content(res)
  tmp <- stringr::str_replace(res_content, '(?s).*"VALUE"\n', '') %>% 
    readr::read_csv(col_types = cols(cat01_code = col_character(), 
                                     cat02_code = col_character(),
                                     cat03_code = col_character(), 
                                     unit = col_character(), 
                                     value = col_character()))
  print(paste0("StartPosition:", posi, " Records:", nrow(tmp)))
  df <- bind_rows(df, tmp)
  if(nrow(tmp) < 100000){
    break
  }
  posi <- posi + 1
}
```

# Data column check

## cat01_code

```{r}
df_cat01_code_uniq <- df %>% distinct(cat01_code, `概況品目(輸入)`)
df_cat01_code_uniq %>% 
  kable(align = "r", caption = paste0("# records : ", nrow(df_cat01_code_uniq))) %>% 
  kable_styling(c("striped","bordered"))
```

## cat02_code

```{r}
df_cat02_code_uniq <- df %>% distinct(cat02_code, `概況品目表の数量・金額`)
df_cat02_code_uniq %>% 
  kable(align = "r", caption = paste0("# records : ", nrow(df_cat02_code_uniq))) %>% 
  kable_styling(c("striped","bordered"))
```


## cat03_code

```{r}
df_cat03_code_uniq <- df %>% distinct(cat03_code, `税関`)
df_cat03_code_uniq %>% 
  kable(align = "r", caption = paste0("# records : ", nrow(df_cat03_code_uniq))) %>% 
  kable_styling(c("striped","bordered"))
```

## area_code

```{r}
df_area_code_uniq <- df %>% distinct(area_code, `国`)
df_area_code_uniq %>% 
  kable(align = "r", caption = paste0("# records : ", nrow(df_area_code_uniq))) %>% 
  kable_styling(c("striped","bordered"))
```


## unit

```{r}
df_unit_uniq <- df %>% distinct(unit)
df_unit_uniq %>% 
  kable(align = "r", caption = paste0("# records : ", nrow(df_unit_uniq))) %>% 
  kable_styling(c("striped","bordered"))
```

## value

MTとかは単位っぽいんだけど、valueずれてる？
https://www.customs.go.jp/toukei/sankou/howto/faq.htm#14

ここから

```{r}
df %>%
  filter(value != "0") -> tmp
tmp %>%
  group_by(value) %>%
  dplyr::summarise(count = n()) -> aaa

df %>%
  filter(value == "ＭＴ") -> bbb
```



