---
title: "Data Model and Experiment"
output: 
  flexdashboard::flex_dashboard:
    theme: paper # good
    orientation: rows
    vertical_layout: scroll # 縦スクロールをいれてくれるので必要
    source_code: embed
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_dir = "../docs/") })
---

```{r setup, include=FALSE}
library(DT)
library(dplyr)
library(knitr)
library(ggplot2)
library(flexdashboard)
library(datamodelr)
```

Row1
-------------------------------------
    
### Data Model

```{r include = F, child = "data01.Rmd"}
```

```{r, fig.width=50, fig.height=20}
# for(r in rel){
#   dm <- dm_add_reference_(dm, table = r[1], column = r[2], ref = r[3], ref_col = r[4])
# }
graph <- dm_create_graph(dm, rankdir = "BT", col_attr = c("column", "type"), edge_attrs = "dir = both, arrowtail = crow, arrowhead = odiamond", columnArrows = F)
dm_render_graph(graph)
```

Row2
-------------------------------------

### Plot1

```{r, fig.width=5, fig.height=5}
ggplot(iris, aes(x =  Sepal.Length, y =  Sepal.Width)) + geom_point()
```

Row3
-------------------------------------

### Plot2

```{r, fig.width=8, fig.height=8}
ggplot(iris, aes(x =  Sepal.Length, y =  Sepal.Width)) + geom_point()
```

Row4
-------------------------------------

### Plot3

```{r, fig.width=20, fig.height=20}
ggplot(iris, aes(x =  Sepal.Length, y =  Sepal.Width)) + geom_point()
```

Row5
-------------------------------------

### DT

```{r}
DT::datatable(bind_cols(iris,iris,iris,iris), rownames = F, 
              extensions = c('Buttons','KeyTable'), 
              options = list(dom = 'Bfrtip', buttons = I('colvis'), keys = TRUE,
                             initComplete = JS("function(settings, json) {","$(this.api().table().header()).css({'background-color': '#666', 'color': '#fff'});","}"))
)
```

Row6 {.tabset .tabset-fade}
-------------------------------------
   
### Chart 2

```{r}
kable(bind_cols(iris,iris,iris,iris)) 
```   
 
### Chart 3
    
```{r}
kable(bind_cols(iris,iris,iris,iris))
```

